### ISSUE TITLE
How to add user from different servers

### ISSUE THREAD

**Issue by GeniusTechnoMystic** [CodeMan99/blitzbot#12]
I was just trying to add my asia ign to blitzbot and it won't let me do it. I have tried putting the server name at various places in the command but it still hasn't worked. And the help command doesn't say anything about how to reference different servers.

Thanks
https://t.co/4hnZwYqY4N

**Comment by CodeMan99** [comment]
You need to specify the region with every command (that requires game data).

```
asia @blitzbot add dannyp777
asia @blitzbot win-rate
asia @blitzbot tank-win-rate Löwe
```

I know this is far from optimal. I need to make the commands themselves region-aware so that I can add some kind of "region mode switching".

**Comment by CodeMan99** [comment]
There is now a "set-region" command. You should be able to do the following now.

```
@blitzbot set-region asia
@blitzbot add dannyp777
@blitzbot tank-win-rate Löwe
```

Prefixing commands with the region should still work as well.
