### ISSUE TITLE
when i ask for win rate

### ISSUE THREAD

**Issue by VETTE333** [CodeMan99/blitzbot#13]
when I ask for win rate it tell me how many I have won and haw many I have played total... it then goes to tell me that since the last time I have asked I have played x number of battles and gives a win rate for those x number of battles... but... whenever anyone else asks for win rate... it only tells them the first part … that they have won x number of battles out of their total... I am the creator of my server and am hoping to figure this out for all my guests... thank you in advance! 

VETTE333Today at 4:51 PM
@blitzbot  wr
blitzbotBOTToday at 4:51 PM
@VETTE333, You have won 5979 of 11373 battles. That is 52.57% victory!
Last time you asked was 156 battles ago, at 52.54% victory.
Over those 156 battles, you won 55.13%!
NEW MESSAGES
DREADNOUGHTToday at 5:51 PM
@blitzbot wr
blitzbotBOTToday at 5:51 PM
@DREADNOUGHT, You have won 10205 of 18653 battles. That is 54.71% victory!

**Comment by CodeMan99** [comment]
Almost certainly a limitation of WarGaming's API. I can only get results from random battles. So clan wars, rating battles, etc are not included.

**Comment by VETTE333** [comment]
Ok. Thank you for the response! I will let my server members know.

**Comment by supinko** [comment]
I've actually noticed the same or similar thing on my server; blitzbot will work for most members, but for some specific members it will only ever show the first line. I've even had them play a random game and then ask for winrate again to verify. The total number of battles does go up, but they never see the "Last time you asked..." part.

**Comment by VETTE333** [comment]
If anyone ever hears of a solution to this problem... please let me know... I would like to get this issue resolved for my server members...

**Comment by supinko** [comment]
@CodeMan99 I believe what's happening is that, with your latest change to win-rate, newly added users won't ever have their database entries updated because they won't ever have an existing entry for "record.battles"; it'll always be undefined, so they'll never get into the "if" clause that updates the results.

**Comment by CodeMan99** [comment]
@supinko Ah ha, you are correct. I deleted a test result that I shouldn't have in 275f0830ca77c94d34a47b77f863fb28ddd303f3. Whoops :blush:

**Comment by CodeMan99** [comment]
blitzbot 3.4.3 has been released. Please re-open if the issue is unresolved.

**Comment by Xela9** [comment]
Hey I am still having this issue where I wont get the “over this many battles” second line after I see the battle count go up on the overall wr count
