### ISSUE TITLE
User suggestions.

### ISSUE THREAD

**Issue by CodeMan99** [CodeMan99/blitzbot#3]
## Modifications
- [ ] add win rating colors (not sure it is possible).
- [x] tighten up mastery-list response, move longer messages to PM.
- [ ] negative argument to mastery-list, allowing you to see what tanks have _not_ earned a badge.
- [ ] some basic filters for mastery-list, like tier or nation.
- [x] short command alias like "wr" for "win-rating".
- [ ] sort tank-win-rate response so it isn't so random in order.
- [ ] sort mastery-list by nation and tier instead of battle count.
- [ ] win-rate history, include average tier for the interval since last check
## New Commands

Most of these are very large tasks. One of the big issues is the need for local database of context information.
- [ ] WN8 / WN7.
- [ ] 30-day history.
- [ ] Track player battle time activity.
- [ ] Parsing names from a screenshot of the "Team" results tab.
- [ ] Platooning aid, maybe use server roles.
- [ ] Survival Rate.
- [ ] Tank Frag tracking.
- [ ] Average damage (or part of the win-rate response).

**Comment by ArMikael** [comment]
I want to suggest two things:

- add **tank-stats [leopard-1]** command that will show current user stats for selected tank. Like Win rate, WN7/WN8, Survival rate, number of battles on this tank. To make it more visually attractive possibly to show the tank picture from Blitz Wiki.      
- add **hangar-tanks** to represent what tanks user currently has in his hangar. This feature is missing in all online blitz-stats-services but could be relevant for many experienced players.

**Comment by CodeMan99** [comment]
The garage information is only provided to users that have authenticated with the service. Allowing users to authenticate is sadly a pain, and even more so since blitzbot is not running in a web browser.
