### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by DobyIR** [CodeMan99/blitzbot#30]
When running the npm install command I get an error at the end stating npm cannot find a file.

PS C:\Users\Ian\Documents\Blitz\CosyBot\blitzbot-master> npm install -g blitzbot-4.0.0.tgz
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ian\AppData\Local\npm-cache\_logs\2023-02-06T18_30_17_283Z-debug-0.log

I have downloaded the zip file to my local drive to run and looked at the log file to see if it would indicate which file is missing but could not find it. 

Any help is appreciated.

**Comment by CodeMan99** [comment]
What are you trying to accomplish? The `blitzbot` project is **not** published on npm.

**Comment by DobyIR** [comment]
Hi Cody,

Thanks for replying so quickly.
I'm trying to build an instance of Blitzbot for my Discord clan server as
the bot has been down for a few weeks and people are going into serious
withdrawal.

I was following the instructions in the Readme file on your github site to
try and build it.

Thx,
Ian

**Comment by CodeMan99** [comment]
Yeah, unfortunately the code of this project is pretty outdated. Which is why it is going down so often.

Anyway, I think the npm error is that it should be relative path when trying to install from the command line. So try `npm install -g ./blitzbot-4.0.0.tgz`. Note the leading `./`.

**Comment by DobyIR** [comment]
I tried your suggestion but still got the same error.  Sounds like even if
I get it to run the bot will suffer the same problem as your instance.

**Comment by CodeMan99** [comment]
> I tried your suggestion but still got the same error.

Dang it. I am using npm v6.14.16 in production. I would hope that's not the problem. However, I've also automated my update process and do pretty in-frequently. So while I've run into this "missing file" issue, I don't remember how to solve it any better.

> Sounds like even if I get it to run the bot will suffer the same problem as your instance.

Likely. I am considering moving it to a better host. However, I'm honestly unsure how many active users blitzbot has anymore. It is difficult for me to judge what my value proposition is.

**Comment by DobyIR** [comment]
I have used it with quite a few different clans in Blitz. All the various
servers I’ve been active on seem to use it. Mostly the old timers in the
game have seen it and used it.

It would be a shame if it disappears.

**Comment by CodeMan99** [comment]
Thanks for the conversation. I won't be making any hasty decisions.

Closing this for now as it seems you've put aside the desire to self-host.

**Comment by DobyIR** [comment]
I may still try to sort out the missing file error as it bugs me it should
be something simple to resolve. Also I enjoy troubleshooting as a way to
learn something new.

Thanks for chatting with me about it.

Cheers,
Ian
