### ISSUE TITLE
Can't install the blitzbot npm package 

### ISSUE THREAD

**Issue by ArMikael** [CodeMan99/blitzbot#6]
I'm getting errors when trying to install the package. Could you check please why the repo is not available?

npm install -g blitzbot-2.3.3.tgz

npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 package could not be found. : blitzbot-2.3.3.tgz
npm ERR! 404
npm ERR! 404  'blitzbot-2.3.3.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by CodeMan99** [comment]
Best laid plans that never got executed. I've since decided to **not** publish to the npmjs.org registry.

Simply put, most users do *not* want an install, and instead just want access to the instance I run.

What is your end goal?

**Comment by ArMikael** [comment]
Thanks for fast answer. I want to run it on our WoT Blitz clan Discord server. It's about 30 active users, but I don't believe that all of them will use it. I will, I like such things. ))

**Comment by CodeMan99** [comment]
If your users are on the North American server (.com), then you can just add my instance. Shoot me an e-mail.

**Comment by ArMikael** [comment]
Nope, we are from EU server. Is there any chance to use your bot in such case?

**Comment by CodeMan99** [comment]
Yup! You will need to add a line [around here](https://github.com/CodeMan99/blitzbot/blob/59a4cf27f97fdf5a3886e7851b39c7c51d118a75/bin/bot.js#L46) to change the region to EU.

```javascript
wotblitz.region = wotblitz.REGION_EU;
```

To create the package you'll install, do `npm pack`. This will create the .tgz file to `npm install -g` later.

The hard part is setting up the "blitzbot.json" ([Step 7 of Installation Setup](https://github.com/CodeMan99/blitzbot#installation-setup)). Let me know how I can help.

**Comment by ArMikael** [comment]
Many thanks, that first time I see the npm pack command. 
I've added the region line to the bot.js and the .tgz file was created successfully.
But now I'm getting another error - 500.

```
> npm install -g blitzbot-2.3.5.tgz.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "blitzbot-2.3.5.tgz."
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E500

npm ERR! Registry returned 500 for GET on https://registry.npmjs.org/blitzbot-2.3.5.tgz.
npm ERR! 
```

Sorry, looks like I don't need at all now. 
`npm install -g` locally on my PC is enough. Let me check.

**Comment by ArMikael** [comment]
Thanks mate, everything works great!

**Comment by CodeMan99** [comment]
What version of `npm` are you using? I do believe that should have worked.

You do need to have have _node v6.x_ or newer to run the bot because of the [discord.js](https://github.com/hydrabolt/discord.js/) dependency. Also, you can safely ignore the warnings from `npm` about missing peer dependencies because those are for doing voice channels, which blitzbot doesn't do currently.

**Comment by CodeMan99** [comment]
If there are any further questions, open a new issue or email me.

**Comment by KhaireGat** [comment]
Hi @ArMikael, can you share this (EU BlitzBot) with us please ?

**Comment by ArMikael** [comment]
@boulangerinfernal there is no need in my version anymore. @CodeMan99 has added option to choose region. So just ready carefully settings docs. 
https://github.com/CodeMan99/blitzbot

**Comment by KhaireGat** [comment]
@ArMikael thank you for your answer but a friend shared with me a faster and easier solution in the meantime. It is to add the NA version of the bot to your server with an invite link and to put "eu" in front of each command.
