### ISSUE TITLE
complicated install!

### ISSUE THREAD

**Issue by helpmeoutbro** [CodeMan99/blitzbot#7]
"this setup is pretty easy however"

Uhm ok explain like this is too a 5 year old with a Windows 10 laptop.
"Create a package that you can install by running npm pack in the repo root."
Ok what is a npm pack and what is a repo root? and where are they?
"Install the resulting package globally: npm install -g blitzbot-2.3.3.tgz."
What are any of these and how do I do this??

I don't understand a single step there im not some hacker person, and what even are steps 1-4 what are they for? 
Please explain this because I want to use your bot but you made it so complicated!

**Comment by CodeMan99** [comment]
What is your reason for installing? If you just want to use the bot, then you may use my instance. If you are wanting to host the bot, then you should have some programming knowledge, and thus my directions are fairly easy.

Poking at my writing because I assume some knowledge of the tools isn't getting you anywhere. I need to make some assumptions for brevity.

**Comment by helpmeoutbro** [comment]
I have a discord group for my clan and I wanted to add it to the group so I
can do @blitzbot win-rate and @blitzbot tank-win-rate and the other
commands as well. I've been in another clan group and it's so useful so I
wanted to add it to my group. I added some bot called "aethex" really
easily from github by just clicking install but I dont see the button here.
How can I make it work

**Comment by CodeMan99** [comment]
I'll email you the link. I intentionally do not distribute the link because of machine constraints.

Alternatively, contact me on Discord. There is a link to my own guild in the [CONTRIBUTING](//github.com/CodeMan99/blitzbot/blob/master/CONTRIBUTING.md#feature-requests) document.
