### ISSUE TITLE
Access to the instance for EU server ?

### ISSUE THREAD

**Issue by canariporsche** [CodeMan99/blitzbot#8]
Hello,
I am not a tech profile and i am running a discord instance for Blitz in EU server.
Is it possible to get access to an EU instance of blitzbot as i am not capable to personaly install and modify all this stuff :-(

Thx in advance for any positive answer :-)

Rgds

**Comment by CodeMan99** [comment]
Send questions to @ArMikael as he (apparently) has an EU instance (see #6).

**Comment by ArMikael** [comment]
@canariporsche Hi mate,
I would love to share my EU Bot-server with you, but it's not running all time. I don't have PC/Mac which running 24/7, so usually I turn it on when needed. 

I can share with you updated files, but you will need to set your tokens and secret keys into blitzbot.json.

**Comment by canariporsche** [comment]
Thx Codeman99 and artmikael for your answers. With the help of one of my tech friend,we wil try to set-it up for Eu server. Will let you know the result ;-)

@Artmikael: is it possible as you proposed to get your updated code ? how can we exchange mail address safely ?

**Comment by canariporsche** [comment]
Code on github is uptodate ?

**Comment by ArMikael** [comment]
@canariporsche take my nickname (check that you writing it right), add number "2" at the end and don't forget to add gmail.com at the end.

**Comment by CodeMan99** [comment]
@ArMikael Would you mind pushing your fork up?

**Comment by ArMikael** [comment]
@CodeMan99 done. If I remember it right there was changes only in one line.

**Comment by CodeMan99** [comment]
FYI guys, I host my own instance of blitzbot on a [Raspberry Pi 3](http://www.mcmelectronics.com/product/83-17300) (running [Raspbian Lite](https://www.raspberrypi.org/downloads/raspbian/)) and have had zero issue with the hardware thus far.

I made sure to get a wall wart that output something 6-8 amps on the USB ports. You do have to watch out for that because most of them output enough to charge an iPhone or less.

**Comment by canariporsche** [comment]
Done !
Works fine and run 24/7 on a server.
Thx guys :-)

**Comment by CodeMan99** [comment]
@canariporsche Out of curiosity, what nickname did you use on discord for the bot?

**Comment by canariporsche** [comment]
Blitz4discord

Envoyé de mon iPhone

**Comment by canariporsche** [comment]
do you want me to release the EU version for everyone ? The server is quite strong and is running 24/7 ?

**Comment by CodeMan99** [comment]
@canariporsche It's up to you who you allow to use your bot. No reason my EULA has to be the same as your EULA.

I intentionally do _not_ distribute the bot URL because I want some control over the memory footprint it has on my limited hardware.

**Comment by CodeMan99** [comment]
@canariporsche Multi-region support inbound! 82e3f57a1eb2dc84b8a7ffa57c0561f63de09a84
